# Setup
title:               Piyush Joshi
tagline:             'TheCodingMantra'
description:         '<i>Some awesome resources for coding and interview preparation.</i>'
url:                 https://thecodingmantra.com
baseurl:             ''
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Piyush Joshi
  url:               https://twitter.com/mdo
  email:             joshipiyush217@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
